### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by mitaubuchi** [cerevo/hyourowgan#1]
Hyourowganのコンパイルで詰まっております。
どうやらTZ10xx_DFP.1.31.1に対応していないためか
DFP_VER=1.31.1にしたら

fatal error: twic_interface.h: No such file or directory
 #include "twic_interface.h"
compilation terminated.
make: *** [build/src/ble.o] Error 1

でつまってしまいました。
何か対処法などあれば
ご教授のほどよろしくお願いいたします。

**Comment by f-okuhara** [comment]
東芝提供のTZ1000 BSPはマイナーバーション間であってもAPIの破壊的変更があります。
Makefileのバージョン定義を変えただけではビルドが通らない組み合わせがあります。
HyouRowGanの場合は1.35.0をご使用ください。

サポート窓口外からのご質問なので、業務時間外の担当エンジニアの私的な回答です。
(株)Cerevoとしての公式見解では無い点はご了承ください。
(実は、このようなサポートは会社から禁止されています...今後のご質問は[サポート窓口](http://www.cerevo.com/ja/support.html)からお願い致します...)

**Comment by mitaubuchi** [comment]
すみませんです。
開発環境を、再構築してやりなおしたら
問題なくコンパイル通りました、ありがとうございます。

以前、Cerevoのサポートに
Windows 8.1デスクトップとのペアリングの仕方を問い合わせたのですが
サポート外と、言う返答だったので残念に思っていました。
基本、できない理由などの説明もありませんでした。

お騒がせして申し訳ありませんでした。
